### ISSUE TITLE
TODO:

### ISSUE THREAD

**Issue by eryk-poradecki** [eryk-poradecki/TP_Escape_IT_Unity#2]
- [x] find a character suitable for presentation room theme
- [x] play audio from the websocket after receiving it
- [x] add elements to the presentation scene
- [x] send a hint request to django on button press
